url='https://video1.getstreamhosting.com:8304/stream'
name='am1430'

split_interval = 60  # Split files every 60 seconds (1 minute)
output_dir = 'tmp'  # Directory to save the audio files

audio_format = 'opus'      # default
storage_format = 'sqlite'   # default
