url='https://video1.getstreamhosting.com:8304/stream'
name='am1430'
format='opus'
split_interval = 3600  # Split files every 3600 seconds (1 hour)
output_dir = 'tmp/am1430'  # Directory to save the audio files