url='https://video1.getstreamhosting.com:8304/stream'
name='am1430'

split_interval = 10  # Split every 10 seconds
output_dir = 'tmp'  # Directory to save the audio files

audio_format = 'opus'      # default
storage_format = 'sqlite'   # default
