url='https://live.amperwave.net/manifest/audacy-knxamaac-imc'
name='knx_news'

split_interval = 10  # Split every 10 seconds
output_dir = 'tmp'  # Directory to save the output files

audio_format = 'opus'      # default
storage_format = 'sqlite'   # default
