config_type = 'record'  # Indicates this is a recording configuration
output_dir = './tmp/recorded_aac'  # Directory to save the output files
api_port = 17000   # Port for the optional API server

[[sessions]]
url = 'https://video1.getstreamhosting.com:8304/stream'
name = 'am1430'
split_interval = 10  # Split every 10 seconds
audio_format = 'aac'     
storage_format = 'sqlite'   # default

# Schedule: record every day from 14:00 UTC to 07:00 UTC (next day)
# This excludes 07:00 to 14:00 UTC
[sessions.schedule]
record_start = "14:00"
record_end = "07:00"

[[sessions]]
url = 'https://live.amperwave.net/manifest/audacy-knxamaac-imc'
name = 'knx_news'
split_interval = 10  # Split every 10 seconds
audio_format = 'aac'     
storage_format = 'sqlite'   # default

# Schedule: record every day from 14:00 UTC to 07:00 UTC (next day)
# This excludes 07:00 to 14:00 UTC
[sessions.schedule]
record_start = "14:00"
record_end = "07:00"
